# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- checkout: self
  persistCredentials: true

- script: |
    npm install -g @angular/cli
    npm install
    npm install -g angular-cli-ghpages
    ng build --prod

  displayName: 'npm install and build'
- script: |
  
    git config --global user.name "Daniel Ornelas"
    git config --global user.email "dornelas4@miners.utep.edu"
    git config --global --list
    npx ngh --no-silent --dir=dist/danielornelasweb/

  displayName: 'deploy to web'


